package game

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Game) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "s":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = nil
			} else {
				if z.State == nil {
					z.State = new(State)
				}
				err = z.State.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
			}
		case "LastTick":
			z.LastTick, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "LastTick")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Game) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "s"
	err = en.Append(0x82, 0xa1, 0x73)
	if err != nil {
		return
	}
	if z.State == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.State.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "State")
			return
		}
	}
	// write "LastTick"
	err = en.Append(0xa8, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteTime(z.LastTick)
	if err != nil {
		err = msgp.WrapError(err, "LastTick")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Game) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "s"
	o = append(o, 0x82, 0xa1, 0x73)
	if z.State == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.State.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "State")
			return
		}
	}
	// string "LastTick"
	o = append(o, 0xa8, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b)
	o = msgp.AppendTime(o, z.LastTick)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Game) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "s":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.State = nil
			} else {
				if z.State == nil {
					z.State = new(State)
				}
				bts, err = z.State.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
			}
		case "LastTick":
			z.LastTick, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastTick")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Game) Msgsize() (s int) {
	s = 1 + 2
	if z.State == nil {
		s += msgp.NilSize
	} else {
		s += z.State.Msgsize()
	}
	s += 9 + msgp.TimeSize
	return
}
